api:
  password: "TELEGRAM_BOT_SERVER_API_PASSWORD"

telegrambot:
  username: "honghui_bot"
  botToken: "5218594007:AAEmv5n6VahO6UTlHxM5rkOVlyESFaJdg4c"

springfox:
  documentation:
    swagger-ui:
      enabled: true
    enabled: true
    swagger:
      v2:
        host: "127.0.0.1:8080"