server:
  port: 8080

spring:
  application:
    name: telegram-bot-server
  profiles:
    # 开发环境为默认环境
    active: dev

# 默认关闭swagger，防止正式环境暴露接口文档
springfox:
  documentation:
    swagger-ui:
      enabled: false
    enabled: false